/**
 * Jadou Planner — single source of truth for every data entity.
 *
 * The registry drives:
 *  - the Prisma schema (server/scripts/gen-prisma.ts)
 *  - server-side validation & coercion (server/src/validate.ts)
 *  - generic forms, tables and filters in the web app
 *
 * Storage conventions (single-user, local app):
 *  - `date`      → "YYYY-MM-DD" string (local day)
 *  - `datetime`  → "YYYY-MM-DDTHH:mm" string (local time, no timezone shifts)
 *  - `time`      → "HH:mm"
 *  - `json`/`tags` → serialized JSON string in SQLite, parsed by the API
 */

export type FieldType =
  | 'string'
  | 'text'
  | 'number'
  | 'money'
  | 'int'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'time'
  | 'enum'
  | 'ref'
  | 'json'
  | 'tags'
  | 'url'
  | 'image'
  | 'color'
  | 'rating';

export interface Option {
  value: string;
  label: string;
  color?: string;
}

export interface FieldDef {
  type: FieldType;
  label: string;
  required?: boolean;
  options?: Option[];
  ref?: string;
  /** what happens to this row when the referenced row is deleted */
  onDelete?: 'cascade' | 'nullify';
  default?: unknown;
  min?: number;
  max?: number;
  /** not shown in generic forms (managed by the app) */
  hidden?: boolean;
  placeholder?: string;
  help?: string;
  /** shown as a column in generic tables */
  list?: boolean;
  /** span both columns in forms */
  wide?: boolean;
}

export interface ResourceDef {
  label: string;
  plural: string;
  titleField: string;
  orderBy: { field: string; dir: 'asc' | 'desc' };
  search: string[];
  /** date field used by global search / analytics */
  dateField?: string;
  fields: Record<string, FieldDef>;
  /** private health data etc. — never sent to AI unless enabled */
  sensitive?: boolean;
}

// ---------------------------------------------------------------- options

export const CATEGORIES: Option[] = [
  { value: 'cours', label: 'Cours', color: '#8E7DBE' },
  { value: 'devoirs', label: 'Devoirs', color: '#B07AA1' },
  { value: 'alternance', label: 'Alternance', color: '#5E8C8A' },
  { value: 'cils', label: 'Cils', color: '#C98B9B' },
  { value: 'sport', label: 'Sport', color: '#D4876C' },
  { value: 'toeic', label: 'TOEIC', color: '#6C8EBF' },
  { value: 'airbnb', label: 'Airbnb', color: '#C9A35F' },
  { value: 'finance', label: 'Finance', color: '#713F4B' },
  { value: 'business', label: 'Business', color: '#9C6B53' },
  { value: 'beaute', label: 'Beauté', color: '#D9A5B3' },
  { value: 'voyage', label: 'Voyage', color: '#7FA7A0' },
  { value: 'sante', label: 'Santé', color: '#8BA77F' },
  { value: 'perso', label: 'Perso', color: '#A39391' },
];

export const PRIORITIES: Option[] = [
  { value: 'low', label: 'Basse', color: '#B9AEB1' },
  { value: 'medium', label: 'Moyenne', color: '#C9A35F' },
  { value: 'high', label: 'Haute', color: '#C98B9B' },
  { value: 'urgent', label: 'Urgente', color: '#713F4B' },
];

export const TASK_STATUS: Option[] = [
  { value: 'todo', label: 'À faire', color: '#B9AEB1' },
  { value: 'doing', label: 'En cours', color: '#C9A35F' },
  { value: 'done', label: 'Terminé', color: '#7FA38A' },
];

export const RECURRENCE: Option[] = [
  { value: 'none', label: 'Aucune' },
  { value: 'daily', label: 'Chaque jour' },
  { value: 'weekdays', label: 'Jours de semaine' },
  { value: 'weekly', label: 'Chaque semaine' },
  { value: 'monthly', label: 'Chaque mois' },
];

export const GOAL_CATEGORIES: Option[] = [
  { value: 'studies', label: 'Études', color: '#8E7DBE' },
  { value: 'toeic', label: 'TOEIC', color: '#6C8EBF' },
  { value: 'career', label: 'Carrière', color: '#5E8C8A' },
  { value: 'fitness', label: 'Fitness', color: '#D4876C' },
  { value: 'money', label: 'Argent', color: '#713F4B' },
  { value: 'lash', label: 'Lash Studio', color: '#C98B9B' },
  { value: 'business', label: 'Business', color: '#9C6B53' },
  { value: 'real_estate', label: 'Immobilier', color: '#C9A35F' },
  { value: 'travel', label: 'Voyages', color: '#7FA7A0' },
  { value: 'lifestyle', label: 'Lifestyle', color: '#D9A5B3' },
  { value: 'personal', label: 'Personnel', color: '#A39391' },
];

export const HORIZONS: Option[] = [
  { value: 'weekly', label: 'Hebdomadaire' },
  { value: 'monthly', label: 'Mensuel' },
  { value: 'quarterly', label: 'Trimestriel' },
  { value: 'yearly', label: 'Annuel' },
  { value: 'long_term', label: 'Long terme' },
];

export const TX_TYPES: Option[] = [
  { value: 'income', label: 'Revenu', color: '#7FA38A' },
  { value: 'expense', label: 'Dépense', color: '#C46A6A' },
  { value: 'transfer', label: 'Virement interne', color: '#8B8185' },
  { value: 'withdrawal', label: 'Retrait', color: '#B9AEB1' },
  { value: 'deposit', label: 'Dépôt', color: '#B9AEB1' },
];

export const TX_CATEGORIES: Option[] = [
  { value: 'salaire', label: 'Salaire / alternance' },
  { value: 'cils', label: 'Activité cils' },
  { value: 'airbnb', label: 'Airbnb' },
  { value: 'business', label: 'Business' },
  { value: 'investissement', label: 'Investissement' },
  { value: 'aides', label: 'Aides / bourses' },
  { value: 'logement', label: 'Logement' },
  { value: 'courses', label: 'Courses' },
  { value: 'restaurants', label: 'Restaurants' },
  { value: 'transport', label: 'Transport' },
  { value: 'abonnements', label: 'Abonnements' },
  { value: 'shopping', label: 'Shopping' },
  { value: 'beaute', label: 'Beauté' },
  { value: 'sport', label: 'Sport' },
  { value: 'sante', label: 'Santé' },
  { value: 'etudes', label: 'Études' },
  { value: 'loisirs', label: 'Loisirs' },
  { value: 'voyages', label: 'Voyages' },
  { value: 'cadeaux', label: 'Cadeaux' },
  { value: 'impots', label: 'Impôts & frais' },
  { value: 'materiel_cils', label: 'Matériel cils' },
  { value: 'epargne', label: 'Épargne' },
  { value: 'autre', label: 'Autre' },
];

export const ACCOUNTS_FOR: Option[] = [
  { value: 'pharmacy', label: 'Pharmacie' },
  { value: 'lash', label: 'Lash Studio' },
];

export const WISHLIST_CATEGORIES: Option[] = [
  { value: 'fashion', label: 'Fashion' },
  { value: 'beauty', label: 'Beauty' },
  { value: 'perfume', label: 'Perfumes' },
  { value: 'haircare', label: 'Haircare' },
  { value: 'skincare', label: 'Skincare' },
  { value: 'tech', label: 'Tech' },
  { value: 'home', label: 'Home' },
  { value: 'travel', label: 'Travel' },
  { value: 'luxury', label: 'Luxury' },
  { value: 'other', label: 'Other' },
];

export const WISHLIST_STATUS: Option[] = [
  { value: 'want', label: 'Want', color: '#C98B9B' },
  { value: 'saving', label: 'Saving For', color: '#C9A35F' },
  { value: 'waiting_sale', label: 'Waiting For Sale', color: '#6C8EBF' },
  { value: 'purchased', label: 'Purchased', color: '#7FA38A' },
  { value: 'archived', label: 'Archived', color: '#B9AEB1' },
];

const yesNoRating = { type: 'rating' as const, min: 1, max: 5 };

// ---------------------------------------------------------------- registry

export const REGISTRY = {
  // ============================== ORGANIZATION
  task: {
    label: 'Tâche',
    plural: 'Tâches',
    titleField: 'title',
    orderBy: { field: 'date', dir: 'asc' },
    search: ['title', 'description', 'notes'],
    dateField: 'date',
    fields: {
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      description: { type: 'text', label: 'Description', wide: true },
      category: { type: 'enum', label: 'Catégorie', options: CATEGORIES, default: 'perso', list: true },
      priority: { type: 'enum', label: 'Priorité', options: PRIORITIES, default: 'medium', list: true },
      date: { type: 'date', label: 'Date', list: true },
      time: { type: 'time', label: 'Heure' },
      durationMin: { type: 'int', label: 'Durée estimée (min)', min: 0 },
      status: { type: 'enum', label: 'Statut', options: TASK_STATUS, default: 'todo', list: true },
      focus: { type: 'boolean', label: 'Priorité du jour (Today’s Focus)', default: false },
      recurrence: { type: 'enum', label: 'Récurrence', options: RECURRENCE, default: 'none' },
      subtasks: { type: 'json', label: 'Sous-tâches', default: [], hidden: true },
      resources: { type: 'text', label: 'Ressources (liens)', wide: true },
      notes: { type: 'text', label: 'Notes', wide: true },
      projectId: { type: 'ref', label: 'Projet de groupe', ref: 'groupProject', onDelete: 'cascade' },
      focusMinutes: { type: 'int', label: 'Temps concentré', default: 0, hidden: true },
      completedAt: { type: 'string', label: 'Terminée le', hidden: true },
      sourceType: { type: 'string', label: 'Source', hidden: true },
      sourceId: { type: 'int', label: 'Source id', hidden: true },
    },
  },
  event: {
    label: 'Événement',
    plural: 'Événements',
    titleField: 'title',
    orderBy: { field: 'start', dir: 'asc' },
    search: ['title', 'location', 'notes'],
    dateField: 'start',
    fields: {
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      category: { type: 'enum', label: 'Catégorie', options: CATEGORIES, default: 'perso', list: true },
      start: { type: 'datetime', label: 'Début', required: true, list: true },
      end: { type: 'datetime', label: 'Fin' },
      allDay: { type: 'boolean', label: 'Toute la journée', default: false },
      location: { type: 'string', label: 'Lieu' },
      recurrence: { type: 'enum', label: 'Récurrence', options: RECURRENCE, default: 'none' },
      recurrenceUntil: { type: 'date', label: 'Récurrence jusqu’au' },
      reminderMin: { type: 'int', label: 'Rappel (minutes avant)', min: 0 },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  goal: {
    label: 'Objectif',
    plural: 'Objectifs',
    titleField: 'title',
    orderBy: { field: 'targetDate', dir: 'asc' },
    search: ['title', 'description'],
    dateField: 'targetDate',
    fields: {
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      description: { type: 'text', label: 'Description', wide: true },
      category: { type: 'enum', label: 'Catégorie', options: GOAL_CATEGORIES, default: 'personal', list: true },
      horizon: { type: 'enum', label: 'Horizon', options: HORIZONS, default: 'monthly', list: true },
      targetDate: { type: 'date', label: 'Date cible', list: true },
      targetValue: { type: 'number', label: 'Valeur cible (optionnel)' },
      currentValue: { type: 'number', label: 'Valeur actuelle' },
      unit: { type: 'string', label: 'Unité', placeholder: '€, séances, points…' },
      progress: { type: 'int', label: 'Progression manuelle (%)', min: 0, max: 100, default: 0 },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'active', label: 'En cours', color: '#C9A35F' },
          { value: 'done', label: 'Atteint', color: '#7FA38A' },
          { value: 'paused', label: 'En pause', color: '#B9AEB1' },
          { value: 'abandoned', label: 'Abandonné', color: '#8B8185' },
        ],
        default: 'active',
        list: true,
      },
      steps: { type: 'json', label: 'Étapes', default: [], hidden: true },
    },
  },
  habit: {
    label: 'Habitude',
    plural: 'Habitudes',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true },
      emoji: { type: 'string', label: 'Emoji', default: '✨' },
      color: { type: 'color', label: 'Couleur', default: '#C98B9B' },
      targetPerWeek: { type: 'int', label: 'Objectif / semaine', default: 5, min: 1, max: 7, list: true },
      autoLink: {
        type: 'enum',
        label: 'Validation automatique',
        help: 'Coche automatiquement le jour quand l’activité liée est enregistrée.',
        options: [
          { value: 'none', label: 'Manuelle' },
          { value: 'sport', label: 'Séance de sport réalisée' },
          { value: 'water', label: 'Objectif d’eau atteint' },
          { value: 'toeic', label: 'Entraînement TOEIC' },
          { value: 'journal', label: 'Note de journal' },
          { value: 'focus', label: 'Session focus' },
          { value: 'skincare', label: 'Routine skincare complète' },
        ],
        default: 'none',
      },
      active: { type: 'boolean', label: 'Active', default: true },
    },
  },
  habitLog: {
    label: 'Validation',
    plural: 'Validations',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: [],
    dateField: 'date',
    fields: {
      habitId: { type: 'ref', label: 'Habitude', ref: 'habit', required: true, onDelete: 'cascade' },
      date: { type: 'date', label: 'Date', required: true },
    },
  },
  journalEntry: {
    label: 'Note de journal',
    plural: 'Journal',
    titleField: 'title',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['title', 'content'],
    dateField: 'date',
    sensitive: true,
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      title: { type: 'string', label: 'Titre', list: true },
      mood: { type: 'rating', label: 'Humeur', min: 1, max: 5 },
      content: { type: 'text', label: 'Texte', wide: true },
      photo: { type: 'image', label: 'Photo' },
      tags: { type: 'tags', label: 'Tags', default: [] },
    },
  },
  focusSession: {
    label: 'Session focus',
    plural: 'Sessions focus',
    titleField: 'label',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['label'],
    dateField: 'date',
    fields: {
      label: { type: 'string', label: 'Libellé' },
      taskId: { type: 'ref', label: 'Tâche', ref: 'task', onDelete: 'nullify' },
      category: { type: 'enum', label: 'Catégorie', options: CATEGORIES, default: 'perso' },
      date: { type: 'date', label: 'Date', required: true },
      minutes: { type: 'int', label: 'Minutes', required: true },
    },
  },
  review: {
    label: 'Bilan',
    plural: 'Bilans',
    titleField: 'period',
    orderBy: { field: 'period', dir: 'desc' },
    search: ['period'],
    fields: {
      type: { type: 'enum', label: 'Type', options: [{ value: 'weekly', label: 'Hebdomadaire' }, { value: 'monthly', label: 'Mensuel' }], required: true },
      period: { type: 'string', label: 'Période', required: true },
      answers: { type: 'json', label: 'Réponses', default: {} },
      priorities: { type: 'json', label: 'Priorités', default: [] },
    },
  },
  routine: {
    label: 'Routine',
    plural: 'Routines',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true },
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'morning', label: 'Matin' },
          { value: 'evening', label: 'Soir' },
          { value: 'skincare_am', label: 'Skincare matin' },
          { value: 'skincare_pm', label: 'Skincare soir' },
          { value: 'hair', label: 'Cheveux' },
          { value: 'sport', label: 'Sport' },
          { value: 'studies', label: 'Études' },
          { value: 'beauty', label: 'Beauté' },
          { value: 'organization', label: 'Organisation' },
        ],
        default: 'morning',
        list: true,
      },
      steps: { type: 'json', label: 'Étapes', default: [], hidden: true },
      active: { type: 'boolean', label: 'Active', default: true },
    },
  },
  routineLog: {
    label: 'Routine réalisée',
    plural: 'Routines réalisées',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: [],
    dateField: 'date',
    fields: {
      routineId: { type: 'ref', label: 'Routine', ref: 'routine', required: true, onDelete: 'cascade' },
      date: { type: 'date', label: 'Date', required: true },
      done: { type: 'json', label: 'Étapes faites', default: [] },
    },
  },
  memory: {
    label: 'Souvenir IA',
    plural: 'Mémoire de Jadou AI',
    titleField: 'content',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['content'],
    fields: {
      content: { type: 'text', label: 'Information', required: true, list: true, wide: true },
      category: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'goal', label: 'Objectif' },
          { value: 'preference', label: 'Préférence' },
          { value: 'project', label: 'Projet' },
          { value: 'habit', label: 'Habitude' },
          { value: 'decision', label: 'Décision' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'preference',
        list: true,
      },
    },
  },
  note: {
    label: 'Note rapide',
    plural: 'Notes rapides',
    titleField: 'content',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['content'],
    fields: {
      content: { type: 'text', label: 'Note', required: true, list: true, wide: true },
      kind: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'note', label: 'Note' },
          { value: 'idea', label: 'Idée' },
        ],
        default: 'note',
        list: true,
      },
      pinned: { type: 'boolean', label: 'Épinglée', default: false },
    },
  },

  // ============================== STUDIES
  course: {
    label: 'Matière',
    plural: 'Matières',
    titleField: 'name',
    orderBy: { field: 'name', dir: 'asc' },
    search: ['name', 'teacher'],
    fields: {
      name: { type: 'string', label: 'Matière', required: true, list: true },
      coefficient: { type: 'number', label: 'Coefficient', default: 1, list: true },
      teacher: { type: 'string', label: 'Intervenant·e', list: true },
      semester: { type: 'string', label: 'Semestre', placeholder: 'S1, S2…' },
      color: { type: 'color', label: 'Couleur', default: '#8E7DBE' },
    },
  },
  homework: {
    label: 'Devoir',
    plural: 'Devoirs',
    titleField: 'title',
    orderBy: { field: 'dueDate', dir: 'asc' },
    search: ['title', 'instructions'],
    dateField: 'dueDate',
    fields: {
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      courseId: { type: 'ref', label: 'Matière', ref: 'course', list: true, onDelete: 'nullify' },
      dueDate: { type: 'date', label: 'Date limite', required: true, list: true },
      dueTime: { type: 'time', label: 'Heure limite' },
      priority: { type: 'enum', label: 'Priorité', options: PRIORITIES, default: 'medium', list: true },
      status: { type: 'enum', label: 'Statut', options: TASK_STATUS, default: 'todo', list: true },
      instructions: { type: 'text', label: 'Consignes', wide: true },
      members: { type: 'string', label: 'Membres du groupe', wide: true },
      documents: { type: 'text', label: 'Documents (liens)', wide: true },
      subtasks: { type: 'json', label: 'Sous-tâches', default: [], hidden: true },
      taskId: { type: 'int', label: 'Tâche liée', hidden: true },
    },
  },
  exam: {
    label: 'Examen',
    plural: 'Examens',
    titleField: 'title',
    orderBy: { field: 'date', dir: 'asc' },
    search: ['title', 'notes'],
    dateField: 'date',
    fields: {
      title: { type: 'string', label: 'Examen', required: true, list: true, wide: true },
      courseId: { type: 'ref', label: 'Matière', ref: 'course', list: true, onDelete: 'nullify' },
      date: { type: 'date', label: 'Date', required: true, list: true },
      time: { type: 'time', label: 'Heure' },
      location: { type: 'string', label: 'Salle / lieu' },
      notes: { type: 'text', label: 'Notes / chapitres', wide: true },
    },
  },
  grade: {
    label: 'Note',
    plural: 'Notes',
    titleField: 'label',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['label'],
    dateField: 'date',
    fields: {
      courseId: { type: 'ref', label: 'Matière', ref: 'course', required: true, list: true, onDelete: 'cascade' },
      label: { type: 'string', label: 'Évaluation', required: true, list: true },
      value: { type: 'number', label: 'Note', required: true, list: true },
      outOf: { type: 'number', label: 'Sur', default: 20 },
      coefficient: { type: 'number', label: 'Coefficient', default: 1, list: true },
      date: { type: 'date', label: 'Date', list: true },
    },
  },
  groupProject: {
    label: 'Projet de groupe',
    plural: 'Projets de groupe',
    titleField: 'title',
    orderBy: { field: 'dueDate', dir: 'asc' },
    search: ['title', 'description'],
    dateField: 'dueDate',
    fields: {
      title: { type: 'string', label: 'Projet', required: true, list: true, wide: true },
      courseId: { type: 'ref', label: 'Matière', ref: 'course', list: true, onDelete: 'nullify' },
      dueDate: { type: 'date', label: 'Rendu', list: true },
      members: { type: 'string', label: 'Membres', wide: true },
      description: { type: 'text', label: 'Description', wide: true },
      documents: { type: 'text', label: 'Documents (liens)', wide: true },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  thesisItem: {
    label: 'Élément du mémoire',
    plural: 'Mémoire',
    titleField: 'title',
    orderBy: { field: 'order', dir: 'asc' },
    search: ['title', 'content'],
    dateField: 'date',
    fields: {
      type: {
        type: 'enum',
        label: 'Section',
        required: true,
        options: [
          { value: 'problem', label: 'Problématique' },
          { value: 'hypothesis', label: 'Hypothèses' },
          { value: 'plan', label: 'Plan' },
          { value: 'source', label: 'Bibliographie' },
          { value: 'research', label: 'Recherches' },
          { value: 'interview', label: 'Entretiens' },
          { value: 'writing', label: 'Rédaction' },
          { value: 'deadline', label: 'Échéances' },
        ],
        list: true,
      },
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      content: { type: 'text', label: 'Contenu', wide: true },
      url: { type: 'url', label: 'Lien' },
      date: { type: 'date', label: 'Date / échéance', list: true },
      words: { type: 'int', label: 'Mots rédigés' },
      status: { type: 'enum', label: 'Statut', options: TASK_STATUS, default: 'todo', list: true },
      order: { type: 'int', label: 'Ordre', default: 0, hidden: true },
    },
  },

  // ============================== TOEIC
  toeicExam: {
    label: 'Score TOEIC',
    plural: 'Scores TOEIC',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['notes'],
    dateField: 'date',
    fields: {
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'official', label: 'Examen officiel' },
          { value: 'mock', label: 'Test blanc' },
          { value: 'planned', label: 'Examen prévu' },
        ],
        default: 'mock',
        list: true,
      },
      date: { type: 'date', label: 'Date', required: true, list: true },
      listening: { type: 'int', label: 'Listening (/495)', min: 0, max: 495, list: true },
      reading: { type: 'int', label: 'Reading (/495)', min: 0, max: 495, list: true },
      total: { type: 'int', label: 'Score total (/990)', min: 0, max: 990, list: true },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  toeicAttempt: {
    label: 'Entraînement',
    plural: 'Entraînements',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: [],
    dateField: 'date',
    fields: {
      part: { type: 'int', label: 'Partie', required: true },
      mode: { type: 'string', label: 'Mode', default: 'practice' },
      score: { type: 'int', label: 'Bonnes réponses', required: true },
      total: { type: 'int', label: 'Questions', required: true },
      durationSec: { type: 'int', label: 'Durée (s)', default: 0 },
      date: { type: 'date', label: 'Date', required: true },
      details: { type: 'json', label: 'Détails', default: [] },
    },
  },
  toeicMistake: {
    label: 'Erreur',
    plural: 'Erreurs',
    titleField: 'notion',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['notion', 'question'],
    dateField: 'date',
    fields: {
      part: { type: 'int', label: 'Partie', list: true },
      questionId: { type: 'string', label: 'Question', hidden: true },
      notion: { type: 'string', label: 'Notion', list: true },
      question: { type: 'text', label: 'Question', wide: true },
      yourAnswer: { type: 'string', label: 'Ma réponse' },
      correctAnswer: { type: 'string', label: 'Bonne réponse' },
      explanation: { type: 'text', label: 'Explication', wide: true },
      reviewed: { type: 'boolean', label: 'Retravaillée', default: false, list: true },
      date: { type: 'date', label: 'Date', list: true },
    },
  },
  flashcard: {
    label: 'Flashcard',
    plural: 'Vocabulary Book',
    titleField: 'word',
    orderBy: { field: 'nextReview', dir: 'asc' },
    search: ['word', 'translation', 'example'],
    fields: {
      word: { type: 'string', label: 'Mot / expression', required: true, list: true },
      translation: { type: 'string', label: 'Traduction', required: true, list: true },
      example: { type: 'text', label: 'Exemple', wide: true },
      theme: { type: 'string', label: 'Thème', placeholder: 'Business, travel, office…', list: true },
      level: {
        type: 'enum',
        label: 'Niveau',
        options: [
          { value: 'new', label: 'Nouveau', color: '#C98B9B' },
          { value: 'learning', label: 'En apprentissage', color: '#C9A35F' },
          { value: 'known', label: 'Maîtrisé', color: '#7FA38A' },
        ],
        default: 'new',
        list: true,
      },
      nextReview: { type: 'date', label: 'Prochaine révision', list: true },
      interval: { type: 'int', label: 'Intervalle (jours)', default: 0, hidden: true },
      ease: { type: 'number', label: 'Facilité', default: 2.5, hidden: true },
      reps: { type: 'int', label: 'Répétitions', default: 0, hidden: true },
    },
  },

  // ============================== FITNESS & WELLNESS
  exercise: {
    label: 'Exercice',
    plural: 'Exercise Library',
    titleField: 'name',
    orderBy: { field: 'name', dir: 'asc' },
    search: ['name', 'muscles', 'equipment'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true },
      category: {
        type: 'enum',
        label: 'Zone',
        options: [
          { value: 'glutes', label: 'Fessiers' },
          { value: 'hamstrings', label: 'Ischio-jambiers' },
          { value: 'quads', label: 'Quadriceps' },
          { value: 'back', label: 'Dos' },
          { value: 'upper', label: 'Haut du corps' },
          { value: 'core', label: 'Abdos / gainage' },
          { value: 'cardio', label: 'Cardio' },
        ],
        default: 'glutes',
        list: true,
      },
      muscles: { type: 'string', label: 'Muscles sollicités', list: true, wide: true },
      equipment: { type: 'string', label: 'Matériel', list: true },
      instructions: { type: 'text', label: 'Instructions', wide: true },
      tips: { type: 'text', label: 'Conseils techniques', wide: true },
      variants: { type: 'text', label: 'Variantes', wide: true },
      media: { type: 'image', label: 'Visuel (votre fichier)' },
      videoUrl: { type: 'url', label: 'Vidéo (lien autorisé)' },
    },
  },
  workoutTemplate: {
    label: 'Programme',
    plural: 'Programmes',
    titleField: 'name',
    orderBy: { field: 'weekday', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Nom de la séance', required: true, list: true },
      weekday: {
        type: 'enum',
        label: 'Jour',
        options: [
          { value: '1', label: 'Lundi' },
          { value: '2', label: 'Mardi' },
          { value: '3', label: 'Mercredi' },
          { value: '4', label: 'Jeudi' },
          { value: '5', label: 'Vendredi' },
          { value: '6', label: 'Samedi' },
          { value: '0', label: 'Dimanche' },
          { value: 'none', label: 'Libre' },
        ],
        default: 'none',
        list: true,
      },
      time: { type: 'time', label: 'Heure habituelle' },
      location: {
        type: 'enum',
        label: 'Lieu',
        options: [
          { value: 'gym', label: 'Salle' },
          { value: 'home', label: 'Maison' },
        ],
        default: 'gym',
        list: true,
      },
      exercises: { type: 'json', label: 'Exercices', default: [], hidden: true },
      notes: { type: 'text', label: 'Notes', wide: true },
      active: { type: 'boolean', label: 'Actif', default: true },
    },
  },
  workoutSession: {
    label: 'Séance',
    plural: 'Séances',
    titleField: 'name',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['name', 'notes'],
    dateField: 'date',
    fields: {
      name: { type: 'string', label: 'Séance', required: true, list: true },
      templateId: { type: 'ref', label: 'Programme', ref: 'workoutTemplate', onDelete: 'nullify' },
      date: { type: 'date', label: 'Date', required: true, list: true },
      time: { type: 'time', label: 'Heure' },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'planned', label: 'Prévue', color: '#C9A35F' },
          { value: 'in_progress', label: 'En cours', color: '#6C8EBF' },
          { value: 'done', label: 'Réalisée', color: '#7FA38A' },
          { value: 'skipped', label: 'Manquée', color: '#B9AEB1' },
        ],
        default: 'planned',
        list: true,
      },
      durationMin: { type: 'int', label: 'Durée (min)', list: true },
      energy: { ...yesNoRating, label: 'Énergie' },
      notes: { type: 'text', label: 'Commentaires', wide: true },
    },
  },
  setLog: {
    label: 'Série',
    plural: 'Séries',
    titleField: 'setIndex',
    orderBy: { field: 'setIndex', dir: 'asc' },
    search: [],
    fields: {
      sessionId: { type: 'ref', label: 'Séance', ref: 'workoutSession', required: true, onDelete: 'cascade' },
      exerciseId: { type: 'ref', label: 'Exercice', ref: 'exercise', required: true, onDelete: 'cascade' },
      setIndex: { type: 'int', label: 'Série', default: 1 },
      reps: { type: 'int', label: 'Répétitions' },
      weight: { type: 'number', label: 'Charge (kg)' },
      done: { type: 'boolean', label: 'Terminée', default: false },
      comment: { type: 'string', label: 'Commentaire' },
    },
  },
  foodLog: {
    label: 'Aliment',
    plural: 'Journal alimentaire',
    titleField: 'name',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['name'],
    dateField: 'date',
    sensitive: true,
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      meal: {
        type: 'enum',
        label: 'Repas',
        options: [
          { value: 'breakfast', label: 'Petit-déjeuner' },
          { value: 'lunch', label: 'Déjeuner' },
          { value: 'dinner', label: 'Dîner' },
          { value: 'snack', label: 'Collation' },
        ],
        default: 'lunch',
        list: true,
      },
      name: { type: 'string', label: 'Aliment', required: true, list: true, wide: true },
      quantity: { type: 'string', label: 'Quantité', placeholder: '150 g, 1 bol…' },
      kcal: { type: 'number', label: 'Calories (estim.)', list: true },
      protein: { type: 'number', label: 'Protéines (g)' },
      carbs: { type: 'number', label: 'Glucides (g)' },
      fat: { type: 'number', label: 'Lipides (g)' },
    },
  },
  recipe: {
    label: 'Recette',
    plural: 'Recettes & favoris',
    titleField: 'name',
    orderBy: { field: 'name', dir: 'asc' },
    search: ['name', 'ingredients'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true, wide: true },
      favorite: { type: 'boolean', label: 'Repas favori', default: false, list: true },
      kcal: { type: 'number', label: 'Calories / portion', list: true },
      protein: { type: 'number', label: 'Protéines (g)' },
      carbs: { type: 'number', label: 'Glucides (g)' },
      fat: { type: 'number', label: 'Lipides (g)' },
      ingredients: { type: 'text', label: 'Ingrédients', wide: true },
      instructions: { type: 'text', label: 'Préparation', wide: true },
      photo: { type: 'image', label: 'Photo' },
    },
  },
  shoppingItem: {
    label: 'Article',
    plural: 'Liste de courses',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Article', required: true, list: true },
      quantity: { type: 'string', label: 'Quantité', list: true },
      aisle: { type: 'string', label: 'Rayon' },
      checked: { type: 'boolean', label: 'Pris', default: false },
    },
  },
  mealPlan: {
    label: 'Repas planifié',
    plural: 'Planning alimentaire',
    titleField: 'label',
    orderBy: { field: 'date', dir: 'asc' },
    search: ['label'],
    dateField: 'date',
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      meal: {
        type: 'enum',
        label: 'Repas',
        options: [
          { value: 'breakfast', label: 'Petit-déjeuner' },
          { value: 'lunch', label: 'Déjeuner' },
          { value: 'dinner', label: 'Dîner' },
          { value: 'snack', label: 'Collation' },
        ],
        default: 'lunch',
        list: true,
      },
      label: { type: 'string', label: 'Repas prévu', required: true, list: true },
      recipeId: { type: 'ref', label: 'Recette', ref: 'recipe', onDelete: 'nullify' },
    },
  },
  waterLog: {
    label: 'Hydratation',
    plural: 'Hydratation',
    titleField: 'date',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: [],
    dateField: 'date',
    fields: {
      date: { type: 'date', label: 'Date', required: true },
      ml: { type: 'int', label: 'Quantité (ml)', required: true },
      time: { type: 'time', label: 'Heure' },
    },
  },
  bodyMetric: {
    label: 'Mesure',
    plural: 'Body Progress',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['notes'],
    dateField: 'date',
    sensitive: true,
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      weight: { type: 'number', label: 'Poids (kg)', list: true },
      waist: { type: 'number', label: 'Tour de taille (cm)', list: true },
      hips: { type: 'number', label: 'Tour de hanches (cm)', list: true },
      glutes: { type: 'number', label: 'Tour de fessiers (cm)', list: true },
      thigh: { type: 'number', label: 'Tour de cuisse (cm)' },
      arm: { type: 'number', label: 'Tour de bras (cm)' },
      photo: { type: 'image', label: 'Photo (facultative, privée)' },
      notes: { type: 'text', label: 'Commentaires', wide: true },
    },
  },
  wellnessLog: {
    label: 'Check-in bien-être',
    plural: 'Wellness',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['notes'],
    dateField: 'date',
    sensitive: true,
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      sleepHours: { type: 'number', label: 'Sommeil (h)', list: true },
      sleepQuality: { ...yesNoRating, label: 'Qualité du sommeil' },
      mood: { ...yesNoRating, label: 'Humeur', list: true },
      energy: { ...yesNoRating, label: 'Énergie', list: true },
      digestion: { ...yesNoRating, label: 'Digestion' },
      period: { type: 'boolean', label: 'Règles (facultatif)', default: false },
      notes: { type: 'text', label: 'Ressenti', wide: true },
    },
  },

  // ============================== PHARMACY & INSTAGRAM
  contentPost: {
    label: 'Publication',
    plural: 'Publications',
    titleField: 'theme',
    orderBy: { field: 'date', dir: 'asc' },
    search: ['theme', 'description', 'hashtags'],
    dateField: 'date',
    fields: {
      account: { type: 'enum', label: 'Compte', options: ACCOUNTS_FOR, default: 'pharmacy', required: true },
      theme: { type: 'string', label: 'Thème / titre', required: true, list: true, wide: true },
      date: { type: 'date', label: 'Date', required: true, list: true },
      time: { type: 'time', label: 'Heure' },
      network: {
        type: 'enum',
        label: 'Réseau',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'facebook', label: 'Facebook' },
        ],
        default: 'instagram',
        list: true,
      },
      format: {
        type: 'enum',
        label: 'Format',
        options: [
          { value: 'post', label: 'Post' },
          { value: 'carousel', label: 'Carrousel' },
          { value: 'reel', label: 'Réel' },
          { value: 'story', label: 'Story' },
          { value: 'video', label: 'Vidéo TikTok' },
          { value: 'before_after', label: 'Avant / après' },
          { value: 'promo', label: 'Promotion' },
          { value: 'availability', label: 'Disponibilités' },
        ],
        default: 'post',
        list: true,
      },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'idea', label: 'Idée', color: '#B9AEB1' },
          { value: 'draft', label: 'Brouillon', color: '#C9A35F' },
          { value: 'ready', label: 'Prête', color: '#6C8EBF' },
          { value: 'published', label: 'Publiée', color: '#7FA38A' },
        ],
        default: 'idea',
        list: true,
      },
      description: { type: 'text', label: 'Description / légende', wide: true },
      hashtags: { type: 'string', label: 'Hashtags', wide: true },
      visual: { type: 'image', label: 'Visuel' },
      campaignId: { type: 'ref', label: 'Campagne', ref: 'campaign', onDelete: 'nullify' },
    },
  },
  campaign: {
    label: 'Campagne',
    plural: 'Campagnes',
    titleField: 'name',
    orderBy: { field: 'start', dir: 'desc' },
    search: ['name', 'objectives', 'results'],
    dateField: 'start',
    fields: {
      name: { type: 'string', label: 'Campagne', required: true, list: true, wide: true },
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'promotion', label: 'Promotion' },
          { value: 'animation', label: 'Animation' },
          { value: 'launch', label: 'Lancement' },
          { value: 'event', label: 'Événement' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'promotion',
        list: true,
      },
      start: { type: 'date', label: 'Début', list: true },
      end: { type: 'date', label: 'Fin', list: true },
      budget: { type: 'money', label: 'Budget', list: true },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'planned', label: 'Prévue', color: '#C9A35F' },
          { value: 'active', label: 'En cours', color: '#6C8EBF' },
          { value: 'done', label: 'Terminée', color: '#7FA38A' },
        ],
        default: 'planned',
        list: true,
      },
      supports: { type: 'text', label: 'Supports', wide: true },
      objectives: { type: 'text', label: 'Objectifs', wide: true },
      results: { type: 'text', label: 'Résultats', wide: true },
    },
  },
  contentAsset: {
    label: 'Contenu',
    plural: 'Content Library',
    titleField: 'title',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['title', 'content', 'tags'],
    fields: {
      account: {
        type: 'enum',
        label: 'Compte',
        options: [...ACCOUNTS_FOR, { value: 'personal', label: 'Perso' }],
        default: 'pharmacy',
        list: true,
      },
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'photo', label: 'Photo' },
          { value: 'video', label: 'Vidéo' },
          { value: 'idea', label: 'Idée' },
          { value: 'text', label: 'Texte' },
          { value: 'visual', label: 'Visuel' },
          { value: 'hashtags', label: 'Hashtags' },
          { value: 'inspiration', label: 'Inspiration' },
          { value: 'document', label: 'Document' },
        ],
        default: 'idea',
        list: true,
      },
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      image: { type: 'image', label: 'Image / fichier' },
      url: { type: 'url', label: 'Lien' },
      content: { type: 'text', label: 'Texte / notes', wide: true },
      tags: { type: 'tags', label: 'Tags', default: [] },
    },
  },
  socialMetric: {
    label: 'Statistiques',
    plural: 'Performance',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['notes'],
    dateField: 'date',
    fields: {
      account: { type: 'enum', label: 'Compte', options: ACCOUNTS_FOR, default: 'pharmacy', required: true, list: true },
      network: {
        type: 'enum',
        label: 'Réseau',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'facebook', label: 'Facebook' },
        ],
        default: 'instagram',
        list: true,
      },
      date: { type: 'date', label: 'Date du relevé', required: true, list: true },
      followers: { type: 'int', label: 'Abonnés', list: true },
      posts: { type: 'int', label: 'Publications' },
      views: { type: 'int', label: 'Vues', list: true },
      reach: { type: 'int', label: 'Portée' },
      interactions: { type: 'int', label: 'Interactions', list: true },
      engagementRate: { type: 'number', label: 'Engagement (%)' },
      source: {
        type: 'enum',
        label: 'Source',
        options: [
          { value: 'manual', label: 'Saisie manuelle' },
          { value: 'api', label: 'API Meta' },
        ],
        default: 'manual',
      },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  inboxRequest: {
    label: 'Demande',
    plural: 'Demandes clientes',
    titleField: 'name',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['name', 'message'],
    dateField: 'date',
    fields: {
      name: { type: 'string', label: 'Contact', required: true, list: true },
      date: { type: 'date', label: 'Date', required: true, list: true },
      channel: {
        type: 'enum',
        label: 'Canal',
        options: [
          { value: 'instagram', label: 'DM Instagram' },
          { value: 'whatsapp', label: 'WhatsApp' },
          { value: 'sms', label: 'SMS' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'instagram',
        list: true,
      },
      message: { type: 'text', label: 'Demande', wide: true },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'new', label: 'Nouvelle', color: '#C98B9B' },
          { value: 'answered', label: 'Répondue', color: '#C9A35F' },
          { value: 'booked', label: 'RDV pris', color: '#7FA38A' },
          { value: 'closed', label: 'Clôturée', color: '#B9AEB1' },
        ],
        default: 'new',
        list: true,
      },
    },
  },

  // ============================== LASH STUDIO
  lashService: {
    label: 'Prestation',
    plural: 'Prestations',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Prestation', required: true, list: true },
      price: { type: 'money', label: 'Prix', list: true },
      durationMin: { type: 'int', label: 'Durée (min)', list: true },
      consumableCost: { type: 'money', label: 'Coût des consommables', list: true },
      description: { type: 'text', label: 'Description', wide: true },
      active: { type: 'boolean', label: 'Active', default: true },
    },
  },
  client: {
    label: 'Cliente',
    plural: 'Clientes',
    titleField: 'name',
    orderBy: { field: 'name', dir: 'asc' },
    search: ['name', 'phone', 'instagram', 'notes'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true },
      phone: { type: 'string', label: 'Téléphone', list: true },
      instagram: { type: 'string', label: 'Instagram' },
      email: { type: 'string', label: 'E-mail' },
      source: {
        type: 'enum',
        label: 'Comment m’avez-vous connue ?',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'word_of_mouth', label: 'Bouche-à-oreille' },
          { value: 'referral', label: 'Parrainage' },
          { value: 'google', label: 'Google' },
          { value: 'other', label: 'Autre' },
        ],
        list: true,
      },
      preferences: { type: 'text', label: 'Préférences (courbure, longueur, épaisseur…)', wide: true },
      allergies: { type: 'string', label: 'Sensibilités / allergies', wide: true },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  lashAppointment: {
    label: 'Rendez-vous',
    plural: 'Rendez-vous cils',
    titleField: 'start',
    orderBy: { field: 'start', dir: 'asc' },
    search: ['notes'],
    dateField: 'start',
    fields: {
      clientId: { type: 'ref', label: 'Cliente', ref: 'client', required: true, list: true, onDelete: 'cascade' },
      serviceId: { type: 'ref', label: 'Prestation', ref: 'lashService', list: true, onDelete: 'nullify' },
      start: { type: 'datetime', label: 'Date & heure', required: true, list: true },
      durationMin: { type: 'int', label: 'Durée (min)', default: 120 },
      price: { type: 'money', label: 'Prix', list: true },
      deposit: { type: 'money', label: 'Acompte', default: 0 },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'booked', label: 'Réservé', color: '#C9A35F' },
          { value: 'confirmed', label: 'Confirmé', color: '#6C8EBF' },
          { value: 'done', label: 'Réalisé', color: '#7FA38A' },
          { value: 'cancelled', label: 'Annulé', color: '#B9AEB1' },
          { value: 'no_show', label: 'Absente', color: '#C46A6A' },
        ],
        default: 'booked',
        list: true,
      },
      paymentStatus: {
        type: 'enum',
        label: 'Paiement',
        options: [
          { value: 'unpaid', label: 'Non payé', color: '#C46A6A' },
          { value: 'deposit', label: 'Acompte reçu', color: '#C9A35F' },
          { value: 'paid', label: 'Encaissé', color: '#7FA38A' },
        ],
        default: 'unpaid',
        list: true,
      },
      paymentMethod: {
        type: 'enum',
        label: 'Moyen de paiement',
        options: [
          { value: 'cash', label: 'Espèces' },
          { value: 'card', label: 'Carte' },
          { value: 'transfer', label: 'Virement' },
          { value: 'paylib', label: 'Paylib / Lydia / Wero' },
        ],
      },
      accountId: { type: 'ref', label: 'Compte d’encaissement', ref: 'bankAccount', onDelete: 'nullify', help: 'Pour alimenter vos revenus lors de l’encaissement.' },
      notes: { type: 'text', label: 'Notes', wide: true },
      transactionId: { type: 'int', label: 'Transaction liée', hidden: true },
    },
  },
  stockItem: {
    label: 'Produit',
    plural: 'Stock',
    titleField: 'name',
    orderBy: { field: 'name', dir: 'asc' },
    search: ['name', 'supplier'],
    fields: {
      name: { type: 'string', label: 'Produit', required: true, list: true },
      category: { type: 'string', label: 'Catégorie', placeholder: 'Colle, cils, patchs…', list: true },
      quantity: { type: 'number', label: 'Quantité', default: 0, list: true },
      unit: { type: 'string', label: 'Unité', placeholder: 'boîtes, flacons…' },
      unitPrice: { type: 'money', label: 'Prix d’achat unitaire', list: true },
      supplier: { type: 'string', label: 'Fournisseur', list: true },
      alertThreshold: { type: 'number', label: 'Seuil d’alerte', default: 1 },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },

  // ============================== MONEY
  bankAccount: {
    label: 'Compte',
    plural: 'Comptes',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name', 'bank'],
    fields: {
      name: { type: 'string', label: 'Nom du compte', required: true, list: true },
      bank: { type: 'string', label: 'Banque', placeholder: 'BoursoBank, Crédit Agricole…', list: true },
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'current', label: 'Compte courant' },
          { value: 'savings', label: 'Épargne' },
          { value: 'investment', label: 'Investissement (PEA, CTO…)' },
          { value: 'cash', label: 'Espèces' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'current',
        list: true,
      },
      initialBalance: { type: 'money', label: 'Solde initial', default: 0, list: true },
      initialDate: { type: 'date', label: 'Date du solde initial' },
      color: { type: 'color', label: 'Couleur', default: '#713F4B' },
      archived: { type: 'boolean', label: 'Archivé', default: false },
    },
  },
  transaction: {
    label: 'Transaction',
    plural: 'Transactions',
    titleField: 'label',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['label', 'notes'],
    dateField: 'date',
    fields: {
      label: { type: 'string', label: 'Libellé', required: true, list: true, wide: true },
      type: { type: 'enum', label: 'Type', options: TX_TYPES, default: 'expense', required: true, list: true },
      amount: { type: 'money', label: 'Montant', required: true, min: 0, list: true },
      date: { type: 'date', label: 'Date', required: true, list: true },
      accountId: { type: 'ref', label: 'Compte', ref: 'bankAccount', required: true, list: true, onDelete: 'cascade' },
      toAccountId: { type: 'ref', label: 'Vers le compte (virement)', ref: 'bankAccount', onDelete: 'nullify' },
      category: { type: 'enum', label: 'Catégorie', options: TX_CATEGORIES, default: 'autre', list: true },
      notes: { type: 'text', label: 'Notes', wide: true },
      sourceType: { type: 'string', label: 'Source', hidden: true },
      sourceId: { type: 'int', label: 'Source id', hidden: true },
      importHash: { type: 'string', label: 'Empreinte import', hidden: true },
    },
  },
  budgetLine: {
    label: 'Ligne de budget',
    plural: 'Budget',
    titleField: 'label',
    orderBy: { field: 'kind', dir: 'asc' },
    search: ['label'],
    fields: {
      month: { type: 'string', label: 'Mois (AAAA-MM) — vide = tous les mois', placeholder: '2026-10' },
      kind: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'income', label: 'Revenus' },
          { value: 'fixed', label: 'Charges fixes' },
          { value: 'variable', label: 'Dépenses variables' },
          { value: 'savings', label: 'Épargne' },
          { value: 'investment', label: 'Investissements' },
        ],
        required: true,
        list: true,
      },
      label: { type: 'string', label: 'Libellé', required: true, list: true },
      category: { type: 'enum', label: 'Catégorie suivie', options: TX_CATEGORIES, list: true, help: 'Pour comparer avec vos dépenses réelles.' },
      amount: { type: 'money', label: 'Montant prévu', required: true, list: true },
    },
  },
  savingsGoal: {
    label: 'Objectif d’épargne',
    plural: 'Savings Goals',
    titleField: 'name',
    orderBy: { field: 'targetDate', dir: 'asc' },
    search: ['name', 'notes'],
    dateField: 'targetDate',
    fields: {
      name: { type: 'string', label: 'Objectif', required: true, list: true, wide: true },
      category: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'safety', label: 'Épargne de sécurité' },
          { value: 'real_estate', label: 'Apport immobilier' },
          { value: 'business', label: 'Futur business' },
          { value: 'travel', label: 'Voyages' },
          { value: 'purchase', label: 'Achat important' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'safety',
        list: true,
      },
      target: { type: 'money', label: 'Montant cible', required: true, list: true },
      initialAmount: { type: 'money', label: 'Déjà économisé', default: 0 },
      targetDate: { type: 'date', label: 'Date cible', list: true },
      accountId: { type: 'ref', label: 'Compte associé', ref: 'bankAccount', onDelete: 'nullify' },
      color: { type: 'color', label: 'Couleur', default: '#713F4B' },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  savingsContribution: {
    label: 'Versement',
    plural: 'Versements',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['note'],
    dateField: 'date',
    fields: {
      goalId: { type: 'ref', label: 'Objectif', ref: 'savingsGoal', required: true, onDelete: 'cascade', list: true },
      date: { type: 'date', label: 'Date', required: true, list: true },
      amount: { type: 'money', label: 'Montant (négatif = retrait)', required: true, list: true },
      note: { type: 'string', label: 'Note' },
    },
  },
  investment: {
    label: 'Investissement',
    plural: 'Investissements',
    titleField: 'asset',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['asset', 'ticker', 'notes'],
    dateField: 'date',
    fields: {
      asset: { type: 'string', label: 'Actif', required: true, list: true, placeholder: 'ETF S&P 500…' },
      ticker: { type: 'string', label: 'Ticker / ISIN', list: true },
      kind: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'etf', label: 'ETF' },
          { value: 'stock', label: 'Action' },
          { value: 'fund', label: 'Fonds' },
          { value: 'crypto', label: 'Crypto' },
          { value: 'bond', label: 'Obligation' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'etf',
        list: true,
      },
      date: { type: 'date', label: 'Date d’achat', required: true, list: true },
      amount: { type: 'money', label: 'Montant investi (frais inclus)', required: true, list: true },
      units: { type: 'number', label: 'Nombre de parts', list: true },
      buyPrice: { type: 'money', label: 'Prix d’achat / part' },
      currentPrice: { type: 'money', label: 'Prix actuel / part', help: 'Mis à jour manuellement.' },
      accountId: { type: 'ref', label: 'Compte / enveloppe', ref: 'bankAccount', onDelete: 'nullify' },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },

  // ============================== REAL ESTATE & AIRBNB
  property: {
    label: 'Bien',
    plural: 'Biens immobiliers',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name', 'city', 'notes'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true },
      city: { type: 'string', label: 'Ville', list: true },
      surface: { type: 'number', label: 'Surface (m²)', list: true },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'owned', label: 'Détenu / géré' },
          { value: 'project', label: 'Projet potentiel' },
          { value: 'sold', label: 'Vendu' },
        ],
        default: 'project',
        list: true,
      },
      ownership: {
        type: 'enum',
        label: 'Détention',
        options: [
          { value: 'personal', label: 'Personnel' },
          { value: 'family', label: 'Familial' },
          { value: 'managed', label: 'Simplement géré' },
        ],
        default: 'personal',
        list: true,
      },
      rentalType: {
        type: 'enum',
        label: 'Location',
        options: [
          { value: 'furnished', label: 'Meublée' },
          { value: 'unfurnished', label: 'Nue' },
          { value: 'airbnb', label: 'Airbnb / saisonnière' },
          { value: 'coliving', label: 'Colocation' },
          { value: 'none', label: 'Non loué' },
        ],
        default: 'furnished',
      },
      price: { type: 'money', label: 'Prix d’achat', list: true },
      fees: { type: 'money', label: 'Frais (notaire, agence)' },
      works: { type: 'money', label: 'Travaux' },
      downPayment: { type: 'money', label: 'Apport' },
      loanAmount: { type: 'money', label: 'Montant du crédit' },
      rate: { type: 'number', label: 'Taux annuel (%)' },
      durationYears: { type: 'int', label: 'Durée (ans)' },
      monthlyPayment: { type: 'money', label: 'Mensualité (vide = calculée)' },
      rent: { type: 'money', label: 'Loyer mensuel', list: true },
      charges: { type: 'money', label: 'Charges mensuelles' },
      propertyTax: { type: 'money', label: 'Taxe foncière annuelle' },
      insurance: { type: 'money', label: 'Assurance mensuelle' },
      taxRate: { type: 'number', label: 'Fiscalité estimée (%)', default: 0 },
      link: { type: 'url', label: 'Annonce' },
      photo: { type: 'image', label: 'Photo' },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  airbnbListing: {
    label: 'Logement',
    plural: 'Logements Airbnb',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name', 'address'],
    fields: {
      name: { type: 'string', label: 'Logement', required: true, list: true },
      propertyId: { type: 'ref', label: 'Bien lié', ref: 'property', onDelete: 'nullify' },
      address: { type: 'string', label: 'Adresse / quartier', list: true },
      nightlyPrice: { type: 'money', label: 'Prix moyen / nuit', list: true },
      cleaningCost: { type: 'money', label: 'Coût du ménage' },
      monthlyCosts: { type: 'money', label: 'Charges mensuelles' },
      photo: { type: 'image', label: 'Photo' },
      notes: { type: 'text', label: 'Infos pratiques (sans codes sensibles)', wide: true },
    },
  },
  airbnbBooking: {
    label: 'Réservation',
    plural: 'Réservations',
    titleField: 'guest',
    orderBy: { field: 'checkIn', dir: 'asc' },
    search: ['guest', 'notes'],
    dateField: 'checkIn',
    fields: {
      listingId: { type: 'ref', label: 'Logement', ref: 'airbnbListing', required: true, list: true, onDelete: 'cascade' },
      guest: { type: 'string', label: 'Voyageur', required: true, list: true },
      checkIn: { type: 'date', label: 'Arrivée', required: true, list: true },
      checkOut: { type: 'date', label: 'Départ', required: true, list: true },
      guests: { type: 'int', label: 'Voyageurs', default: 1 },
      amount: { type: 'money', label: 'Montant (versé par voyageur)', list: true },
      fees: { type: 'money', label: 'Frais (plateforme, ménage…)', default: 0 },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'inquiry', label: 'Demande', color: '#B9AEB1' },
          { value: 'confirmed', label: 'Confirmée', color: '#6C8EBF' },
          { value: 'paid', label: 'Payée', color: '#7FA38A' },
          { value: 'cancelled', label: 'Annulée', color: '#C46A6A' },
        ],
        default: 'confirmed',
        list: true,
      },
      accountId: { type: 'ref', label: 'Compte de versement', ref: 'bankAccount', onDelete: 'nullify' },
      notes: { type: 'text', label: 'Notes', wide: true },
      transactionId: { type: 'int', label: 'Transaction liée', hidden: true },
    },
  },
  messageTemplate: {
    label: 'Modèle de message',
    plural: 'Modèles de messages',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name', 'body'],
    fields: {
      context: {
        type: 'enum',
        label: 'Contexte',
        options: [
          { value: 'airbnb', label: 'Airbnb' },
          { value: 'lash', label: 'Lash Studio' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'airbnb',
        list: true,
      },
      name: { type: 'string', label: 'Nom', required: true, list: true },
      body: { type: 'text', label: 'Message', required: true, wide: true },
    },
  },

  // ============================== ENTREPRENEURSHIP
  businessIdea: {
    label: 'Idée business',
    plural: 'Business Ideas',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['name', 'description', 'sector'],
    fields: {
      name: { type: 'string', label: 'Nom', required: true, list: true, wide: true },
      description: { type: 'text', label: 'Description', wide: true },
      sector: { type: 'string', label: 'Secteur', list: true },
      audience: { type: 'string', label: 'Clientèle cible' },
      budget: { type: 'money', label: 'Budget estimé', list: true },
      potential: { type: 'rating', label: 'Potentiel', min: 1, max: 5, list: true },
      difficulty: { type: 'rating', label: 'Difficulté', min: 1, max: 5, list: true },
      stage: {
        type: 'enum',
        label: 'Étape',
        options: [
          { value: 'idea', label: 'Idée' },
          { value: 'market', label: 'Étude de marché' },
          { value: 'competition', label: 'Concurrence' },
          { value: 'model', label: 'Business model' },
          { value: 'budget', label: 'Budget' },
          { value: 'communication', label: 'Communication' },
          { value: 'launch', label: 'Lancement' },
          { value: 'growth', label: 'Développement' },
        ],
        default: 'idea',
        list: true,
      },
      risks: { type: 'text', label: 'Risques', wide: true },
      notes: { type: 'text', label: 'Notes', wide: true },
      roadmap: { type: 'json', label: 'Roadmap', default: {}, hidden: true },
    },
  },
  sideHustle: {
    label: 'Side hustle',
    plural: 'Side Hustles',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'asc' },
    search: ['name'],
    fields: {
      name: { type: 'string', label: 'Activité', required: true, list: true },
      description: { type: 'text', label: 'Description', wide: true },
      monthlyGoal: { type: 'money', label: 'Objectif mensuel', list: true },
      active: { type: 'boolean', label: 'Active', default: true },
    },
  },
  sideHustleLog: {
    label: 'Entrée',
    plural: 'Suivi side hustles',
    titleField: 'date',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['note'],
    dateField: 'date',
    fields: {
      hustleId: { type: 'ref', label: 'Activité', ref: 'sideHustle', required: true, list: true, onDelete: 'cascade' },
      date: { type: 'date', label: 'Date', required: true, list: true },
      revenue: { type: 'money', label: 'Revenus', default: 0, list: true },
      expense: { type: 'money', label: 'Dépenses', default: 0, list: true },
      hours: { type: 'number', label: 'Heures', default: 0, list: true },
      note: { type: 'string', label: 'Note' },
    },
  },

  // ============================== LIFESTYLE
  wishlistItem: {
    label: 'Produit',
    plural: 'Wishlist',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['name', 'brand', 'notes'],
    fields: {
      name: { type: 'string', label: 'Produit', required: true, list: true, wide: true },
      brand: { type: 'string', label: 'Marque', list: true },
      category: { type: 'enum', label: 'Catégorie', options: WISHLIST_CATEGORIES, default: 'other', list: true },
      price: { type: 'money', label: 'Prix', list: true },
      image: { type: 'image', label: 'Photo' },
      link: { type: 'url', label: 'Lien' },
      size: { type: 'string', label: 'Taille' },
      color: { type: 'string', label: 'Couleur' },
      priority: { type: 'enum', label: 'Priorité', options: PRIORITIES.slice(0, 3), default: 'medium', list: true },
      status: { type: 'enum', label: 'Statut', options: WISHLIST_STATUS, default: 'want', list: true },
      savingsGoalId: { type: 'ref', label: 'Objectif d’épargne lié', ref: 'savingsGoal', onDelete: 'nullify' },
      accountId: { type: 'ref', label: 'Compte de paiement (à l’achat)', ref: 'bankAccount', onDelete: 'nullify', help: 'Si renseigné, l’achat crée la dépense automatiquement.' },
      purchasedAt: { type: 'date', label: 'Acheté le' },
      notes: { type: 'text', label: 'Notes', wide: true },
      transactionId: { type: 'int', label: 'Transaction liée', hidden: true },
    },
  },
  beautyProduct: {
    label: 'Produit beauté',
    plural: 'Produits beauté',
    titleField: 'name',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['name', 'brand', 'notes'],
    fields: {
      name: { type: 'string', label: 'Produit', required: true, list: true },
      brand: { type: 'string', label: 'Marque', list: true },
      category: {
        type: 'enum',
        label: 'Catégorie',
        options: [
          { value: 'haircare', label: 'Haircare' },
          { value: 'skincare', label: 'Skincare' },
          { value: 'bodycare', label: 'Bodycare' },
          { value: 'nails', label: 'Nails' },
          { value: 'lashes', label: 'Lashes' },
          { value: 'makeup', label: 'Makeup' },
          { value: 'perfume', label: 'Parfum' },
        ],
        default: 'skincare',
        list: true,
      },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'in_use', label: 'En cours', color: '#7FA38A' },
          { value: 'to_rebuy', label: 'À racheter', color: '#C98B9B' },
          { value: 'stock', label: 'En réserve', color: '#6C8EBF' },
          { value: 'finished', label: 'Terminé', color: '#B9AEB1' },
        ],
        default: 'in_use',
        list: true,
      },
      price: { type: 'money', label: 'Prix', list: true },
      openedAt: { type: 'date', label: 'Ouvert le' },
      rating: { type: 'rating', label: 'Résultat', min: 1, max: 5 },
      image: { type: 'image', label: 'Photo' },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  hairLog: {
    label: 'Soin cheveux',
    plural: 'Haircare Tracker',
    titleField: 'treatment',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['treatment', 'products', 'notes'],
    dateField: 'date',
    fields: {
      date: { type: 'date', label: 'Date', required: true, list: true },
      treatment: { type: 'string', label: 'Soin', required: true, list: true, placeholder: 'Masque, bain d’huile, coupe…' },
      products: { type: 'string', label: 'Produits', list: true },
      lengthCm: { type: 'number', label: 'Longueur (cm)' },
      shine: { type: 'rating', label: 'Brillance', min: 1, max: 5 },
      quality: { type: 'rating', label: 'Qualité', min: 1, max: 5 },
      photo: { type: 'image', label: 'Photo de progression' },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  trip: {
    label: 'Voyage',
    plural: 'Voyages',
    titleField: 'destination',
    orderBy: { field: 'start', dir: 'asc' },
    search: ['destination', 'notes', 'activities'],
    dateField: 'start',
    fields: {
      destination: { type: 'string', label: 'Destination', required: true, list: true },
      start: { type: 'date', label: 'Départ', list: true },
      end: { type: 'date', label: 'Retour', list: true },
      status: {
        type: 'enum',
        label: 'Statut',
        options: [
          { value: 'idea', label: 'Envie' },
          { value: 'planned', label: 'En préparation' },
          { value: 'booked', label: 'Réservé' },
          { value: 'done', label: 'Terminé' },
        ],
        default: 'idea',
        list: true,
      },
      budget: { type: 'money', label: 'Budget', list: true },
      flights: { type: 'text', label: 'Vols', wide: true },
      accommodation: { type: 'text', label: 'Hébergement', wide: true },
      activities: { type: 'text', label: 'Activités', wide: true },
      reservations: { type: 'text', label: 'Réservations', wide: true },
      documents: { type: 'text', label: 'Documents (passeport, assurance…)', wide: true },
      cover: { type: 'image', label: 'Photo de couverture' },
      checklist: { type: 'json', label: 'Checklist', default: [], hidden: true },
      notes: { type: 'text', label: 'Notes', wide: true },
    },
  },
  tripExpense: {
    label: 'Dépense voyage',
    plural: 'Dépenses voyage',
    titleField: 'label',
    orderBy: { field: 'date', dir: 'desc' },
    search: ['label'],
    dateField: 'date',
    fields: {
      tripId: { type: 'ref', label: 'Voyage', ref: 'trip', required: true, onDelete: 'cascade', list: true },
      label: { type: 'string', label: 'Libellé', required: true, list: true },
      amount: { type: 'money', label: 'Montant', required: true, list: true },
      date: { type: 'date', label: 'Date', list: true },
      category: {
        type: 'enum',
        label: 'Catégorie',
        options: [
          { value: 'transport', label: 'Transport' },
          { value: 'lodging', label: 'Hébergement' },
          { value: 'food', label: 'Restauration' },
          { value: 'activity', label: 'Activités' },
          { value: 'shopping', label: 'Shopping' },
          { value: 'other', label: 'Autre' },
        ],
        default: 'other',
        list: true,
      },
    },
  },
  tripPhoto: {
    label: 'Photo',
    plural: 'Galerie',
    titleField: 'caption',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['caption'],
    fields: {
      tripId: { type: 'ref', label: 'Voyage', ref: 'trip', required: true, onDelete: 'cascade' },
      image: { type: 'image', label: 'Photo', required: true },
      caption: { type: 'string', label: 'Légende' },
    },
  },
  visionItem: {
    label: 'Inspiration',
    plural: 'Vision Board',
    titleField: 'title',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['title', 'text'],
    fields: {
      category: {
        type: 'enum',
        label: 'Catégorie',
        options: [
          { value: 'business', label: 'Business' },
          { value: 'money', label: 'Money' },
          { value: 'fitness', label: 'Fitness' },
          { value: 'career', label: 'Career' },
          { value: 'real_estate', label: 'Real Estate' },
          { value: 'travel', label: 'Travel' },
          { value: 'lifestyle', label: 'Lifestyle' },
        ],
        default: 'lifestyle',
        list: true,
      },
      kind: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'image', label: 'Photo' },
          { value: 'quote', label: 'Citation' },
          { value: 'goal', label: 'Objectif' },
          { value: 'inspiration', label: 'Inspiration' },
        ],
        default: 'image',
        list: true,
      },
      title: { type: 'string', label: 'Titre', list: true },
      text: { type: 'text', label: 'Texte / citation', wide: true },
      image: { type: 'image', label: 'Image' },
      goalId: { type: 'ref', label: 'Objectif lié', ref: 'goal', onDelete: 'nullify' },
    },
  },
  resource: {
    label: 'Ressource',
    plural: 'Resource Hub',
    titleField: 'title',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['title', 'notes', 'folder', 'tags'],
    fields: {
      title: { type: 'string', label: 'Titre', required: true, list: true, wide: true },
      type: {
        type: 'enum',
        label: 'Type',
        options: [
          { value: 'pdf', label: 'PDF' },
          { value: 'document', label: 'Document' },
          { value: 'image', label: 'Image' },
          { value: 'link', label: 'Lien' },
          { value: 'video', label: 'Vidéo' },
          { value: 'audio', label: 'Audio' },
          { value: 'note', label: 'Note' },
          { value: 'sheet', label: 'Fiche' },
          { value: 'table', label: 'Tableau' },
          { value: 'template', label: 'Modèle' },
        ],
        default: 'link',
        list: true,
      },
      folder: {
        type: 'enum',
        label: 'Dossier',
        options: [
          { value: 'general', label: 'Général' },
          { value: 'studies', label: 'Études' },
          { value: 'toeic', label: 'TOEIC' },
          { value: 'pharmacy', label: 'Pharmacie' },
          { value: 'lash', label: 'Lash Studio' },
          { value: 'business', label: 'Business' },
          { value: 'finance', label: 'Finance' },
          { value: 'real_estate', label: 'Immobilier' },
          { value: 'airbnb', label: 'Airbnb' },
          { value: 'fitness', label: 'Fitness' },
          { value: 'beauty', label: 'Beauté' },
          { value: 'travel', label: 'Voyages' },
        ],
        default: 'general',
        list: true,
      },
      url: { type: 'url', label: 'Lien' },
      file: { type: 'image', label: 'Fichier' },
      notes: { type: 'text', label: 'Notes / contenu', wide: true },
      tags: { type: 'tags', label: 'Tags', default: [] },
      favorite: { type: 'boolean', label: 'Favori', default: false, list: true },
    },
  },
  resourcePlan: {
    label: 'Plan de ressources',
    plural: 'Resource Planning',
    titleField: 'title',
    orderBy: { field: 'createdAt', dir: 'desc' },
    search: ['title', 'objective'],
    fields: {
      title: { type: 'string', label: 'Plan', required: true, list: true, wide: true },
      objective: { type: 'text', label: 'Objectif', wide: true },
      goalId: { type: 'ref', label: 'Objectif lié', ref: 'goal', onDelete: 'nullify' },
      budget: { type: 'money', label: 'Budget', list: true },
      timeEstimate: { type: 'string', label: 'Temps estimé', list: true },
      resources: { type: 'text', label: 'Ressources', wide: true },
      steps: { type: 'json', label: 'Étapes', default: [], hidden: true },
    },
  },
} satisfies Record<string, ResourceDef>;

export type ResourceName = keyof typeof REGISTRY;
export const RESOURCE_NAMES = Object.keys(REGISTRY) as ResourceName[];

export function getResource(name: string): ResourceDef | undefined {
  return (REGISTRY as Record<string, ResourceDef>)[name];
}

export function optionLabel(options: Option[] | undefined, value: unknown): string {
  if (value == null || value === '') return '';
  return options?.find((o) => o.value === String(value))?.label ?? String(value);
}

export function optionColor(options: Option[] | undefined, value: unknown): string | undefined {
  return options?.find((o) => o.value === String(value))?.color;
}

export function categoryColor(cat: string | null | undefined): string {
  return CATEGORIES.find((c) => c.value === cat)?.color ?? '#A39391';
}
