// Generates server/prisma/schema.prisma from shared/registry.ts
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { REGISTRY, type FieldDef } from '../../shared/registry';

const here = dirname(fileURLToPath(import.meta.url));

const prismaType = (f: FieldDef): string => {
  switch (f.type) {
    case 'number':
    case 'money':
      return 'Float';
    case 'int':
    case 'rating':
    case 'ref':
      return 'Int';
    case 'boolean':
      return 'Boolean';
    default:
      return 'String';
  }
};

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

let out = `// ⚠️ Generated by server/scripts/gen-prisma.ts from shared/registry.ts — do not edit by hand.
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id           Int      @id @default(autoincrement())
  name         String
  passwordHash String
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}

model Session {
  id        String   @id
  userId    Int
  expiresAt DateTime
  createdAt DateTime @default(now())
}

model Setting {
  key       String   @id
  value     String
  updatedAt DateTime @updatedAt
}

model FileAsset {
  id           Int      @id @default(autoincrement())
  storedName   String   @unique
  originalName String
  mime         String
  size         Int
  createdAt    DateTime @default(now())
}

model VaultFile {
  id           Int      @id @default(autoincrement())
  storedName   String   @unique
  originalName String
  mime         String
  size         Int
  iv           String
  tag          String
  note         String?
  createdAt    DateTime @default(now())
}

model ChatMessage {
  id        Int      @id @default(autoincrement())
  role      String
  content   String
  actions   String?
  createdAt DateTime @default(now())
}
`;

for (const [name, def] of Object.entries(REGISTRY)) {
  out += `\nmodel ${cap(name)} {\n  id        Int      @id @default(autoincrement())\n`;
  const indexes: string[] = [];
  for (const [fname, f] of Object.entries(def.fields as Record<string, FieldDef>)) {
    out += `  ${fname} ${prismaType(f)}?\n`;
    if (f.type === 'ref' || f.type === 'date' || f.type === 'datetime') indexes.push(fname);
    if (fname === 'sourceId') indexes.push(fname);
  }
  out += `  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n`;
  for (const i of indexes) out += `  @@index([${i}])\n`;
  out += `}\n`;
}

writeFileSync(join(here, '../prisma/schema.prisma'), out);
console.log('✓ schema.prisma generated with', Object.keys(REGISTRY).length, 'registry models');
